quarkus:
  datasource: 
    db-kind: postgresql
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jdbc:
      url: jdbc:postgresql://productdb:5432/products
  hibernate-orm:
    database: 
      generation: drop-and-create

  package:
    type: mutable-jar
  live-reload: 
    password: livereloadpassword 
    url: http://localhost:8081
  # redis:
    # hosts: redit://cache:6379

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql
